server:
  port: 8086

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:suneetha.nutala2013@gmail.com}
    password: ${MAIL_PASSWORD:Srivathsava*12}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
